import jsPDF from 'jspdf'
import * as XLSX from 'xlsx'
import { format } from 'date-fns'

class ReportService {
  static async generatePDFReport(data, title = 'Sustainability Report') {
    const doc = new jsPDF()
    
    // Title
    doc.setFontSize(20)
    doc.setTextColor(45, 125, 98)
    doc.text(title, 20, 20)
    
    // Date
    doc.setFontSize(10)
    doc.setTextColor(100, 100, 100)
    doc.text(`Generated: ${format(new Date(), 'PPP p')}`, 20, 30)
    
    let yPosition = 45
    
    // Executive Summary
    doc.setFontSize(14)
    doc.setTextColor(0, 0, 0)
    doc.text('Executive Summary', 20, yPosition)
    yPosition += 10
    
    doc.setFontSize(10)
    doc.setTextColor(60, 60, 60)
    const summary = data.summary || 'This report provides an overview of campus sustainability metrics, including carbon emissions, energy consumption, water usage, waste management, and SDG progress.'
    const splitSummary = doc.splitTextToSize(summary, 170)
    doc.text(splitSummary, 20, yPosition)
    yPosition += splitSummary.length * 6 + 10
    
    // Metrics Section
    doc.setFontSize(14)
    doc.setTextColor(0, 0, 0)
    doc.text('Key Metrics', 20, yPosition)
    yPosition += 10
    
    if (data.metrics) {
      Object.entries(data.metrics).forEach(([key, value]) => {
        doc.setFontSize(10)
        doc.setTextColor(60, 60, 60)
        doc.text(`${key}: ${value}`, 25, yPosition)
        yPosition += 7
      })
    }
    
    yPosition += 10
    
    // AI Insights
    if (data.aiInsights && data.aiInsights.length > 0) {
      doc.setFontSize(14)
      doc.setTextColor(0, 0, 0)
      doc.text('AI-Generated Insights', 20, yPosition)
      yPosition += 10
      
      data.aiInsights.forEach((insight, index) => {
        doc.setFontSize(10)
        doc.setTextColor(60, 60, 60)
        const splitInsight = doc.splitTextToSize(`${index + 1}. ${insight}`, 170)
        doc.text(splitInsight, 25, yPosition)
        yPosition += splitInsight.length * 6 + 5
      })
    }
    
    yPosition += 10
    
    // Recommendations
    if (data.recommendations && data.recommendations.length > 0) {
      doc.setFontSize(14)
      doc.setTextColor(0, 0, 0)
      doc.text('Recommendations', 20, yPosition)
      yPosition += 10
      
      data.recommendations.forEach((rec, index) => {
        doc.setFontSize(10)
        doc.setTextColor(60, 60, 60)
        const splitRec = doc.splitTextToSize(`${index + 1}. ${rec}`, 170)
        doc.text(splitRec, 25, yPosition)
        yPosition += splitRec.length * 6 + 5
      })
    }
    
    // Footer
    doc.setFontSize(8)
    doc.setTextColor(150, 150, 150)
    doc.text('Generated by EcoCampus AI', 20, 280)
    doc.text('Page 1 of 1', 170, 280)
    
    return doc
  }
  
  static async generateExcelReport(data, filename = 'sustainability-report.xlsx') {
    const workbook = XLSX.utils.book_new()
    
    // Summary Sheet
    const summaryData = [
      ['Report Title', 'Sustainability Report'],
      ['Generated Date', format(new Date(), 'PPP p')],
      [''],
      ['Executive Summary', data.summary || ''],
      [''],
      ['Key Metrics'],
      ...Object.entries(data.metrics || {}).map(([key, value]) => [key, value])
    ]
    
    const summarySheet = XLSX.utils.aoa_to_sheet(summaryData)
    XLSX.utils.book_append_sheet(workbook, summarySheet, 'Summary')
    
    // AI Insights Sheet
    if (data.aiInsights && data.aiInsights.length > 0) {
      const insightsData = [
        ['#', 'AI-Generated Insight'],
        ...data.aiInsights.map((insight, index) => [index + 1, insight])
      ]
      const insightsSheet = XLSX.utils.aoa_to_sheet(insightsData)
      XLSX.utils.book_append_sheet(workbook, insightsSheet, 'AI Insights')
    }
    
    // Recommendations Sheet
    if (data.recommendations && data.recommendations.length > 0) {
      const recsData = [
        ['#', 'Recommendation', 'Priority', 'Impact'],
        ...data.recommendations.map((rec, index) => [
          index + 1,
          rec.action || rec,
          rec.priority || 'Medium',
          rec.impact || 'N/A'
        ])
      ]
      const recsSheet = XLSX.utils.aoa_to_sheet(recsData)
      XLSX.utils.book_append_sheet(workbook, recsSheet, 'Recommendations')
    }
    
    // SDG Progress Sheet
    if (data.sdgProgress) {
      const sdgData = [
        ['SDG', 'Name', 'Progress %', 'Status'],
        ...Object.entries(data.sdgProgress).map(([key, value]) => [
          key,
          value.name || key,
          value.progress || 0,
          value.status || 'On Track'
        ])
      ]
      const sdgSheet = XLSX.utils.aoa_to_sheet(sdgData)
      XLSX.utils.book_append_sheet(workbook, sdgSheet, 'SDG Progress')
    }
    
    XLSX.writeFile(workbook, filename)
    return filename
  }
  
  static async generateCSVReport(data, filename = 'sustainability-report.csv') {
    const csvData = [
      ['Category', 'Metric', 'Value', 'Date'],
      ['Summary', 'Report Generated', format(new Date(), 'PPP p'), new Date().toISOString()],
      ['']
    ]
    
    // Add metrics
    if (data.metrics) {
      Object.entries(data.metrics).forEach(([key, value]) => {
        csvData.push(['Metric', key, value, new Date().toISOString()])
      })
    }
    
    csvData.push([''])
    
    // Add AI insights
    if (data.aiInsights && data.aiInsights.length > 0) {
      csvData.push(['AI Insights'])
      data.aiInsights.forEach((insight, index) => {
        csvData.push(['Insight', index + 1, insight, new Date().toISOString()])
      })
    }
    
    csvData.push([''])
    
    // Add recommendations
    if (data.recommendations && data.recommendations.length > 0) {
      csvData.push(['Recommendations'])
      data.recommendations.forEach((rec, index) => {
        csvData.push(['Recommendation', index + 1, rec.action || rec, new Date().toISOString()])
      })
    }
    
    const csvContent = csvData.map(row => row.join(',')).join('\n')
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' })
    const link = document.createElement('a')
    link.href = URL.createObjectURL(blob)
    link.download = filename
    link.click()
    
    return filename
  }
  
  static async generateReportData() {
    // Generate comprehensive report data from current state
    return {
      title: 'EcoCampus Sustainability Report',
      summary: 'This comprehensive report analyzes campus sustainability performance across key metrics including carbon emissions, energy consumption, water usage, waste management, and SDG progress. AI-powered insights and recommendations are provided to guide improvement strategies.',
      metrics: {
        'Carbon Emissions': '358 tCO₂e',
        'Electricity Usage': '485 kWh',
        'Water Consumption': '12,500 liters',
        'Waste Generation': '245 kg',
        'Recycling Rate': '62%',
        'Sustainability Score': '78/100',
        'Renewable Energy Mix': '42%'
      },
      aiInsights: [
        'Energy efficiency has improved by 8% from last month due to solar panel installation',
        'Water consumption requires immediate attention - up 5% from baseline',
        'Waste recycling rate is improving but still below 80% target',
        'Carbon emissions are on track to meet 2040 net-zero goal'
      ],
      recommendations: [
        { action: 'Reduce electricity usage in Building A', priority: 'high', impact: '15% reduction' },
        { action: 'Increase recycling in Block C', priority: 'high', impact: '25% landfill diversion' },
        { action: 'Implement water conservation in Hostel 2', priority: 'medium', impact: '12% reduction' },
        { action: 'Expand solar panel coverage', priority: 'medium', impact: '10% renewable increase' }
      ],
      sdgProgress: {
        'SDG 6': { name: 'Clean Water', progress: 72, status: 'On Track' },
        'SDG 7': { name: 'Clean Energy', progress: 85, status: 'Ahead' },
        'SDG 12': { name: 'Responsible Consumption', progress: 64, status: 'Needs Attention' },
        'SDG 13': { name: 'Climate Action', progress: 78, status: 'On Track' }
      }
    }
  }
}

export default ReportService
